{
 "title": "Device Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"device_4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"device_5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "up{job=\"device_4\"}",
     "legendFormat": "Device 4"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"device_4\"} - node_memory_MemFree_bytes{job=\"device_4\"}) / node_memory_MemTotal_bytes{job=\"device_4\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{job=\"device_4\", mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"device_4\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "up{job=\"device_5\"}",
     "legendFormat": "Device 5"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"device_5\"} - node_memory_MemFree_bytes{job=\"device_5\"}) / node_memory_MemTotal_bytes{job=\"device_5\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{job=\"device_5\", mountpoint=\"/\"} / node_filesystem_size_bytes{job=\"device_5\", mountpoint=\"/\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}